# Generated by Django 4.1.4 on 2022-12-09 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sending_emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='emailforsending',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_group', to='sending_emails.groupemail', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='emailforsending',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
