version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  nginx:
    restart: always
    depends_on:
      - web
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
  media_volume: